"""Vendor the fonts the web console uses into gkmas_delta/web/fonts/.

The console runs offline, so fonts ship with the app instead of coming from a
CDN. Each family is Fontsource's variable-weight build, pre-sliced by unicode
range: the browser only fetches the slices a page actually needs, even though
all of them sit on disk.

    python tools/fetch_fonts.py

Versions and npm integrity hashes are pinned; a download that doesn't match is
rejected before anything is unpacked.
"""

import base64
import hashlib
import io
import re
import shutil
import sys
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "gkmas_delta" / "web" / "fonts"
VERSION = "5.3.0"

# package name -> npm sha512 integrity for VERSION
PACKAGES = {
    # Chinese UI text.
    "noto-sans-sc": "sha512-lNar1dF7Ik/lHNPo/7JWG0TolXY29LtsqYgMvEysooZ5bsO9uH4shJmRrwyJ3PjyTPljhpMJEK0jDuLSU4vJ1w==",
    # Japanese in sans: speaker names, file names shown in lang="ja" blocks.
    "noto-sans-jp": "sha512-XVL9GfGBRjj523v9w3Bctu4mNq7E5rUa+AMZm8DK1EM3LAGlKC3DZMvuqkLn4DB4TwwoAjcsJUCiRpUTDzzOkw==",
    # Story text.
    "noto-serif-jp": "sha512-+kD6gj7RhZ8bjA8WxT5UxnwqWUCcFhCaM2t30zjKTS1sAXbDmJEdj+mrCEYIof1SjDy43VElQQCITouTvrGNuA==",
    # File names, versions, sizes, the log.
    "noto-sans-mono": "sha512-EgozyWG4nG2U1OT+zfdyHP1L8O0fUFMUBOilVF9urTshqIdfeGV9/FUQxaNHdPvHtV1cQCs1Ql0W1q93SiPK2w==",
    # The "gkmas-delta" wordmark.
    "quicksand": "sha512-EMyoXnGC0uIbjyHDB01MTJoQuODsMo7Q/4XLEwN97YJEeV1WIVFI0QBiW2exGnxvhnMHb+IwQ9E5QZDgGMWCHw==",
}
TARBALL = "https://registry.npmjs.org/@fontsource-variable/{name}/-/{name}-{version}.tgz"
URL_IN_CSS = re.compile(r"url\(\./files/([^)]+)\)")


def log(message: str) -> None:
    print(f">>> {message}", flush=True)


def fetch(name: str, integrity: str) -> tarfile.TarFile:
    url = TARBALL.format(name=name, version=VERSION)
    log(f"下载 {url}")
    with urllib.request.urlopen(url, timeout=120) as response:
        data = response.read()
    algorithm, expected = integrity.split("-", 1)
    actual = base64.b64encode(hashlib.new(algorithm, data).digest()).decode()
    if actual != expected:
        raise SystemExit(f"{name} 的校验值不对，已丢弃。")
    return tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")


def vendor(name: str, archive: tarfile.TarFile) -> str:
    """Copy the woff2 files index.css refers to; return that CSS with local urls."""
    css = archive.extractfile("package/index.css").read().decode("utf-8")
    target = OUT / name
    target.mkdir(parents=True, exist_ok=True)
    wanted = set(URL_IN_CSS.findall(css))
    for filename in wanted:
        if "/" in filename or not filename.endswith(".woff2"):
            raise SystemExit(f"{name}: 意外的文件引用 {filename}")
        member = archive.extractfile(f"package/files/{filename}")
        (target / filename).write_bytes(member.read())
    (target / "LICENSE").write_bytes(archive.extractfile("package/LICENSE").read())
    log(f"  {name}: {len(wanted)} 个字体切片")
    # Relative to fonts.css itself, which is served from /fonts/.
    return URL_IN_CSS.sub(lambda m: f"url({name}/{m.group(1)})", css)


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    sheets = [f"/* Noto and Quicksand fonts via Fontsource {VERSION}, SIL Open Font License 1.1. Generated by tools/fetch_fonts.py. */\n"]
    for name, integrity in PACKAGES.items():
        with fetch(name, integrity) as archive:
            sheets.append(vendor(name, archive))
    (OUT / "fonts.css").write_text("\n".join(sheets), encoding="utf-8", newline="\n")
    size = sum(f.stat().st_size for f in OUT.rglob("*") if f.is_file()) / 1024 / 1024
    log(f"完成：{OUT}（{size:.1f} MB）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
